// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Streaming Service App UI',
  githubRepoUrl: 'https://github.com/devefy/Flutter-Streaming-Service-App-UI',
  orientation: Orientation.portrait,
  description: 'A standalone streaming‑service home screen UI with custom icons and bottom navigation.',
);
