// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Analog',
  githubRepoUrl: 'https://github.com/aditya-kd/flutter_clock_analog',
  orientation: Orientation.landscape,
  description: 'A standalone analog clock with custom theming and animations.',
);
