// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterCardSwipe',
  githubRepoUrl: 'https://github.com/geekruchika/FlutterCardSwipe',
  orientation: Orientation.portrait,
  description: 'A Tinder‑style card swipe animation demo in Flutter.',
);
