// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Hecksclock',
  githubRepoUrl: 'https://github.com/Germain-L/hecksclock',
  orientation: Orientation.landscape,
  description: 'A colorful clock that changes its background based on the current time.',
);
