// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App',
  githubRepoUrl: 'https://github.com/itsherifAhmed/clock-App',
  orientation: Orientation.landscape,
  description: 'A custom animated clock widget with theme switching.',
);
