// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App Flutter',
  githubRepoUrl: 'https://github.com/rashidwassan/clock-app-flutter',
  orientation: Orientation.landscape,
  description: 'A stylish animated clock with custom painter and icon buttons.',
);
