// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Tick',
  githubRepoUrl: 'https://github.com/ksadanand172/Clock-Tick',
  orientation: Orientation.landscape,
  description: 'A neumorphic analog and digital clock with animated pendulum.',
);
