// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Binary Clock',
  githubRepoUrl: 'https://github.com/adcaine/flutter_binary_clock',
  orientation: Orientation.landscape,
  description: 'Animated binary clock visualizing time with glowing light‑bulb bits.',
);
