// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Adaptive Master Detail Layouts',
  githubRepoUrl: 'https://github.com/roughike/adaptive-master-detail-layouts',
  orientation: null,
  description: 'Demo of an adaptive master‑detail layout that switches between list‑detail and split view.',
);
