// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Story App UI',
  githubRepoUrl: 'https://github.com/devefy/Flutter-Story-App-UI',
  orientation: Orientation.portrait,
  description: 'A visually rich story card carousel UI demo for Flutter.',
);
