// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/Wizpna/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A standalone animated clock face built with Flutter.',
);
