// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Onboarding UI Concept',
  githubRepoUrl: 'https://github.com/CODEHOMIE/Flutter-Onboarding-UI-Concept',
  orientation: Orientation.portrait,
  description: 'A beautiful onboarding flow with animated slides for mobile apps.',
);
