// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/Ankitmahadik/FlutterClock',
  orientation: Orientation.landscape,
  description: 'A visually appealing animated Flutter clock demo.',
);
