// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Freehand Clock',
  githubRepoUrl: 'https://github.com/thayesx/freehand_clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock face built with Flutter.',
);
