// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Sber Portal Clock',
  githubRepoUrl: 'https://github.com/TohaRG2/sber_portal_clock',
  orientation: Orientation.landscape,
  description: 'A standalone digital clock with adjustable colors and brightness.',
);
