// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Math Clock',
  githubRepoUrl: 'https://github.com/MarcelGarus/math_clock',
  orientation: Orientation.landscape,
  description: 'A math‑themed clock displaying animated expressions instead of numbers.',
);
