// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'GhostRigger',
  githubRepoUrl: 'https://github.com/Float-like-a-dash-Sting-like-a-dart/GhostRigger',
  orientation: Orientation.landscape,
  description: 'A cyberpunk‑styled puzzle game demo with animated graphics on a single screen.',
);
