// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'OrigamiFlutterClock',
  githubRepoUrl: 'https://github.com/nitobes/OrigamiFlutterClock',
  orientation: Orientation.landscape,
  description: 'An origami‑style animated clock using Flare for digit transitions.',
);
