// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Face',
  githubRepoUrl: 'https://github.com/prashant3285/clock_face',
  orientation: Orientation.landscape,
  description: 'A simple animated digital clock face built with Flutter.',
);
