// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'TODOAppUI',
  githubRepoUrl: 'https://github.com/d3xvn/TODOAppUI',
  orientation: Orientation.portrait,
  description: 'A visually appealing single‑screen TODO UI with animated color transitions and card list.',
);
