// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'SolarClock',
  githubRepoUrl: 'https://github.com/pol-chen/SolarClock',
  orientation: Orientation.landscape,
  description: 'A solar‑system themed clock with animated sun, earth, and moon.',
);
