// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'KA Clock',
  githubRepoUrl: 'https://github.com/ltdangkhoa/Flutter-KA-Clock',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock face widget for Flutter.',
);
