// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Stempeluhr',
  githubRepoUrl: 'https://github.com/flokau/stempeluhr',
  orientation: Orientation.portrait,
  description: 'Fullscreen clock displaying current time with a start button.',
);
