// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Fluttersignatureview',
  githubRepoUrl: 'https://github.com/iampawan/fluttersignatureview',
  orientation: null,
  description: 'A simple signature capture canvas where you can draw and clear your strokes.',
);
