// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Context Menu',
  githubRepoUrl: 'https://github.com/gskinnerTeam/flutter-context-menu',
  orientation: null,
  description: 'Customizable context menus',
);
