// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Typhoon Clock',
  githubRepoUrl: 'https://github.com/rocktyphoon/typhoon_clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with light/dark themes and weather overlay.',
);
