// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Flutter',
  githubRepoUrl: 'https://github.com/RenatoLucasMota/analog_clock_flutter',
  orientation: Orientation.landscape,
  description: 'A standalone animated analog clock widget for Flutter.',
);
