// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Login Page UI',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-Login-Page-UI',
  orientation: Orientation.portrait,
  description: 'A visually appealing animated login page demo for Flutter.',
);
