// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Tensorflow Lite Flutter',
  githubRepoUrl: 'https://github.com/umair13adil/tensorflow_lite_flutter',
  orientation: Orientation.portrait,
  description: 'Live camera view classifies wall colors with confidence overlay.',
);
