// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Retrosf Clock',
  githubRepoUrl: 'https://github.com/ilikerobots/retrosf_clock',
  orientation: Orientation.landscape,
  description: 'A lo‑fi sci‑fi themed clock with animated retro computer‑style UI.',
);
