// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Job List Application',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-job-list-application',
  orientation: Orientation.portrait,
  description: 'A visually appealing job list UI with fade‑in animations, runnable as a standalone Flutter app.',
);
