// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flutterweb Github Dataviz',
  githubRepoUrl: 'https://github.com/larvalabs/flutterweb_github_dataviz',
  orientation: null,
  description: 'Animated layered chart visualising Flutter GitHub activity.',
);
