// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Bimsina Clock',
  githubRepoUrl: 'https://github.com/bimsina/bimsina_clock',
  orientation: Orientation.landscape,
  description: 'A visually animated clock face demo for Flutter.',
);
