// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'BananaMon',
  githubRepoUrl: 'https://github.com/hglfng/flutter_BananaMon',
  orientation: Orientation.landscape,
  description: 'A bombman-like game written in Flutter with a single-screen UI experience.',
);
