// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Neumorph Clock FlutterClockChallenge',
  githubRepoUrl: 'https://github.com/Adarsh-Mohanty/Neumorph_Clock_FlutterClockChallenge',
  orientation: Orientation.landscape,
  description: 'A standalone neumorphic clock demo showcasing custom UI and animation.',
);
