// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flutterui Hiretalent',
  githubRepoUrl: 'https://github.com/rajayogan/flutterui-hiretalent',
  orientation: Orientation.portrait,
  description: 'A clean talent hiring screen UI built with Flutter.',
);
