// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Onboarding',
  githubRepoUrl: 'https://github.com/devefy/Flutter-Onboarding',
  orientation: Orientation.portrait,
  description: 'A visually rich onboarding flow with animated pages and gradient text.',
);
