// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clockify',
  githubRepoUrl: 'https://github.com/codewithjaspreet/clockify',
  orientation: Orientation.portrait,
  description: 'A beautiful animated clock widget with timezone display on a single screen.',
);
