// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Kline',
  githubRepoUrl: 'https://github.com/zhaojijin/flutter_kline',
  orientation: null,
  description: 'A standalone K‑line candlestick chart widget with interactive demo.',
);
