// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'AnalogClock Flutter',
  githubRepoUrl: 'https://github.com/amndalsr/AnalogClock_flutter',
  orientation: Orientation.landscape,
  description: 'A clean, animated analog clock widget for Flutter.',
);
