// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Justclock',
  githubRepoUrl: 'https://github.com/olgeer/justclock',
  orientation: Orientation.landscape,
  description: 'A configurable digital clock widget with customizable layout and styles.',
);
