// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Buy Ticket Design',
  githubRepoUrl: 'https://github.com/MarcinusX/buy_ticket_design',
  orientation: Orientation.portrait,
  description: 'A beautiful, animated ticket UI demo with parallax cards and a draggable bottom sheet.',
);
