// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Snake Clock',
  githubRepoUrl: 'https://github.com/GilDev/SnakeClock',
  orientation: Orientation.landscape,
  description: 'A playful clock where a snake moves to show the time.',
);
