// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/JustinFincher/FlutterClock',
  orientation: Orientation.landscape,
  description: 'A dynamic conic clock with adaptive colors and weather cues.',
);
