// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: '3d Clock',
  githubRepoUrl: 'https://github.com/AYoungXXX/3d_clock',
  orientation: Orientation.landscape,
  description: 'A 3D flip clock widget with smooth animations, ready to run as a standalone UI demo.',
);
