// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/ahsanalidev/flutter_clock',
  orientation: Orientation.landscape,
  description: 'Animated Flutter clock with custom hands and background effects.',
);
