// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Cool Card Swiper',
  githubRepoUrl: 'https://github.com/Roaa94/flutter_cool_card_swiper',
  orientation: Orientation.portrait,
  description: 'An interactive stacked card swiper with rotation, scaling, and drag animations.',
);
