// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/Fabian-Stein/flutterClock',
  orientation: Orientation.landscape,
  description: 'A sleek, animated clock face demo for the Flutter Clock challenge.',
);
