// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Facebook Redesign',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-Facebook-Redesign',
  orientation: Orientation.portrait,
  description: 'A visually rich, animated Facebook redesign UI demo for Flutter.',
);
