// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/kttailor/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A minimalist analog clock with animated hands and theme switching.',
);
