import 'package:flutter/material.dart';

import 'components/style/palette.dart';

Map<ClockColor, Color> _dark(Map<ClockColor, Color> overrides) => {
  ...Palette.base,
  ...Palette.dark,
  ...Palette.vibrantDark,
  ...overrides,
};

Map<ClockColor, Color> _darkSubtle(Map<ClockColor, Color> overrides) => {
  ...Palette.base,
  ...Palette.dark,
  ...Palette.subtleDark,
  ...overrides,
};

Map<ClockColor, Color> _light(Map<ClockColor, Color> overrides) => {
  ...Palette.base,
  ...Palette.light,
  ...Palette.vibrantLight,
  ...overrides,
};

Map<ClockColor, Color> _lightSubtle(Map<ClockColor, Color> overrides) => {
  ...Palette.base,
  ...Palette.light,
  ...Palette.subtleLight,
  ...overrides,
};

class ClockPalette {
  final String name;
  final bool isDark;
  final Map<ClockColor, Color> colors;

  ClockPalette({
    required this.name,
    required this.isDark,
    required this.colors,
  });
}

final List<ClockPalette> allClockPalettes = [
  // ── Dark palettes ──────────────────────────────────────────────────────────
  ClockPalette(name: 'Vibrant Dark', isDark: true, colors: _dark({})),
  ClockPalette(name: 'Subtle Dark', isDark: true, colors: _darkSubtle({})),
  ClockPalette(
    name: 'Neon Noir',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff0a0a0f),
      ClockColor.goo: const Color(0xff050509),
      ClockColor.analogTimeBackground: const Color(0xff1a004d),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff6600cc),
      ClockColor.ballPrimary: const Color(0xff00ffcc),
      ClockColor.ballSecondary: const Color(0xff004d3d),
      ClockColor.slidePrimary: const Color(0xff001a33),
      ClockColor.slideSecondary: const Color(0xff00ccff),
      ClockColor.weatherBackground: const Color(0xff1a0033),
      ClockColor.weatherBackgroundHighlight: const Color(0xffcc00ff),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff1a0033),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff080013),
      ClockColor.petals: const Color(0xffff00cc),
      ClockColor.petalsHighlight: const Color(0xffff80e5),
      ClockColor.hourHand: const Color(0xff00ffcc),
      ClockColor.minuteHand: const Color(0xffffffff),
      ClockColor.secondHand: const Color(0xffff00cc),
      ClockColor.weatherArrow: const Color(0xff00ffcc),
      ClockColor.thermometerMount: const Color(0xff444444),
    }),
  ),
  ClockPalette(
    name: 'Crimson Night',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff0d0000),
      ClockColor.goo: const Color(0xff050000),
      ClockColor.analogTimeBackground: const Color(0xff8b0000),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffcc0000),
      ClockColor.ballPrimary: const Color(0xffcc2200),
      ClockColor.ballSecondary: const Color(0xff3d0000),
      ClockColor.slidePrimary: const Color(0xff3d0000),
      ClockColor.slideSecondary: const Color(0xff800000),
      ClockColor.weatherBackground: const Color(0xff4d0000),
      ClockColor.weatherBackgroundHighlight: const Color(0xffcc0000),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff4d0000),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff1a0000),
      ClockColor.petals: const Color(0xffcc0000),
      ClockColor.petalsHighlight: const Color(0xffff4444),
      ClockColor.hourHand: const Color(0xffffaaaa),
      ClockColor.minuteHand: const Color(0xffffffff),
      ClockColor.secondHand: const Color(0xffff6666),
      ClockColor.weatherArrow: const Color(0xffffaaaa),
      ClockColor.thermometerMount: const Color(0xff555555),
    }),
  ),
  ClockPalette(
    name: 'Deep Ocean',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff000d1a),
      ClockColor.goo: const Color(0xff00050d),
      ClockColor.analogTimeBackground: const Color(0xff003366),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff0066cc),
      ClockColor.ballPrimary: const Color(0xff005599),
      ClockColor.ballSecondary: const Color(0xff001a33),
      ClockColor.slidePrimary: const Color(0xff001a33),
      ClockColor.slideSecondary: const Color(0xff0055aa),
      ClockColor.weatherBackground: const Color(0xff002244),
      ClockColor.weatherBackgroundHighlight: const Color(0xff0055bb),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff002244),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff000d1a),
      ClockColor.petals: const Color(0xff0066cc),
      ClockColor.petalsHighlight: const Color(0xff66aaff),
      ClockColor.hourHand: const Color(0xff99ccff),
      ClockColor.minuteHand: const Color(0xffccddff),
      ClockColor.secondHand: const Color(0xff66aaff),
      ClockColor.weatherArrow: const Color(0xff99ccff),
      ClockColor.thermometerMount: const Color(0xff336699),
    }),
  ),
  ClockPalette(
    name: 'Forest Night',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff020d04),
      ClockColor.goo: const Color(0xff010702),
      ClockColor.analogTimeBackground: const Color(0xff1a4d1a),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff2d8c2d),
      ClockColor.ballPrimary: const Color(0xff2d6e2d),
      ClockColor.ballSecondary: const Color(0xff0d260d),
      ClockColor.slidePrimary: const Color(0xff0d260d),
      ClockColor.slideSecondary: const Color(0xff336633),
      ClockColor.weatherBackground: const Color(0xff1a3d1a),
      ClockColor.weatherBackgroundHighlight: const Color(0xff2d6e2d),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff1a3d1a),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff0a1a0a),
      ClockColor.petals: const Color(0xff3d8c3d),
      ClockColor.petalsHighlight: const Color(0xff66cc66),
      ClockColor.hourHand: const Color(0xff99dd99),
      ClockColor.minuteHand: const Color(0xffcceecc),
      ClockColor.secondHand: const Color(0xff66cc66),
      ClockColor.weatherArrow: const Color(0xff99dd99),
      ClockColor.thermometerMount: const Color(0xff445544),
    }),
  ),
  ClockPalette(
    name: 'Amber Dusk',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff1a0e00),
      ClockColor.goo: const Color(0xff0d0700),
      ClockColor.analogTimeBackground: const Color(0xff804000),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffcc6600),
      ClockColor.ballPrimary: const Color(0xffcc7700),
      ClockColor.ballSecondary: const Color(0xff401f00),
      ClockColor.slidePrimary: const Color(0xff401f00),
      ClockColor.slideSecondary: const Color(0xffaa5500),
      ClockColor.weatherBackground: const Color(0xff4d2600),
      ClockColor.weatherBackgroundHighlight: const Color(0xffcc6600),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff4d2600),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff1a0d00),
      ClockColor.petals: const Color(0xffdd8800),
      ClockColor.petalsHighlight: const Color(0xffffbb44),
      ClockColor.hourHand: const Color(0xffffcc88),
      ClockColor.minuteHand: const Color(0xffffeecc),
      ClockColor.secondHand: const Color(0xffffaa44),
      ClockColor.weatherArrow: const Color(0xffffcc88),
      ClockColor.thermometerMount: const Color(0xff664422),
    }),
  ),
  ClockPalette(
    name: 'Aurora',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff060914),
      ClockColor.goo: const Color(0xff030609),
      ClockColor.analogTimeBackground: const Color(0xff1a3d2b),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff2db37f),
      ClockColor.ballPrimary: const Color(0xff1a8c5e),
      ClockColor.ballSecondary: const Color(0xff0d2b1e),
      ClockColor.slidePrimary: const Color(0xff1a0d33),
      ClockColor.slideSecondary: const Color(0xff8c2db3),
      ClockColor.weatherBackground: const Color(0xff1a1a40),
      ClockColor.weatherBackgroundHighlight: const Color(0xff6633cc),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff1a1a3d),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff0a0a1a),
      ClockColor.petals: const Color(0xff2db37f),
      ClockColor.petalsHighlight: const Color(0xff77eebb),
      ClockColor.hourHand: const Color(0xff77eebb),
      ClockColor.minuteHand: const Color(0xffccffee),
      ClockColor.secondHand: const Color(0xffaa55ff),
      ClockColor.weatherArrow: const Color(0xff77eebb),
      ClockColor.thermometerMount: const Color(0xff334455),
    }),
  ),
  ClockPalette(
    name: 'Rose Gold',
    isDark: true,
    colors: _dark({
      ClockColor.background: const Color(0xff1a0d10),
      ClockColor.goo: const Color(0xff0d060a),
      ClockColor.analogTimeBackground: const Color(0xff7a3d4d),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffcc6680),
      ClockColor.ballPrimary: const Color(0xffb5697d),
      ClockColor.ballSecondary: const Color(0xff3d1a22),
      ClockColor.slidePrimary: const Color(0xff3d1a22),
      ClockColor.slideSecondary: const Color(0xff9e5566),
      ClockColor.weatherBackground: const Color(0xff4d2230),
      ClockColor.weatherBackgroundHighlight: const Color(0xffcc6680),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff4d2230),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff1a0d10),
      ClockColor.petals: const Color(0xffcc8899),
      ClockColor.petalsHighlight: const Color(0xffffbbcc),
      ClockColor.hourHand: const Color(0xffffccdd),
      ClockColor.minuteHand: const Color(0xfffff0f3),
      ClockColor.secondHand: const Color(0xffffaabb),
      ClockColor.weatherArrow: const Color(0xffffccdd),
      ClockColor.thermometerMount: const Color(0xff664455),
    }),
  ),
  ClockPalette(
    name: 'Slate',
    isDark: true,
    colors: _darkSubtle({
      ClockColor.background: const Color(0xff1a1d2e),
      ClockColor.goo: const Color(0xff0d0f1a),
      ClockColor.analogTimeBackground: const Color(0xff2d3352),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff4d5580),
      ClockColor.ballPrimary: const Color(0xff4d5580),
      ClockColor.ballSecondary: const Color(0xff1a1d33),
      ClockColor.slidePrimary: const Color(0xff1a1d33),
      ClockColor.slideSecondary: const Color(0xff3d4466),
      ClockColor.weatherBackground: const Color(0xff252840),
      ClockColor.weatherBackgroundHighlight: const Color(0xff4d5580),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff252840),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff0f1020),
      ClockColor.petals: const Color(0xff6677aa),
      ClockColor.petalsHighlight: const Color(0xff99aacc),
      ClockColor.hourHand: const Color(0xffaabbdd),
      ClockColor.minuteHand: const Color(0xffccddf0),
      ClockColor.secondHand: const Color(0xff8899cc),
      ClockColor.weatherArrow: const Color(0xffaabbdd),
      ClockColor.thermometerMount: const Color(0xff4d5566),
    }),
  ),

  // ── Light palettes ─────────────────────────────────────────────────────────
  ClockPalette(name: 'Vibrant Light', isDark: false, colors: _light({})),
  ClockPalette(name: 'Subtle Light', isDark: false, colors: _lightSubtle({})),
  ClockPalette(
    name: 'Sky Blue',
    isDark: false,
    colors: _light({
      ClockColor.background: const Color(0xffadd8f6),
      ClockColor.goo: const Color(0xff5aaddb),
      ClockColor.analogTimeBackground: const Color(0xff87ceeb),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffc8e8ff),
      ClockColor.weatherBackground: const Color(0xff6ab4d6),
      ClockColor.weatherBackgroundHighlight: const Color(0xffe8f6ff),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff6ab4d6),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff9dd0ed),
      ClockColor.slidePrimary: const Color(0xff5aaddb),
      ClockColor.slideSecondary: const Color(0xff2980b9),
      ClockColor.ballPrimary: const Color(0xff5aaddb),
      ClockColor.ballSecondary: const Color(0xff1e6e9e),
      ClockColor.petals: const Color(0xff87ceeb),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.thermometerTube: const Color(0xffd8eef9),
      ClockColor.thermometerMount: const Color(0xff5aaddb),
      ClockColor.hourHand: const Color(0xff1e6e9e),
      ClockColor.minuteHand: const Color(0xff0d4466),
      ClockColor.secondHand: const Color(0xff2980b9),
      ClockColor.weatherArrow: const Color(0xff1e6e9e),
    }),
  ),
  ClockPalette(
    name: 'Mint',
    isDark: false,
    colors: _light({
      ClockColor.background: const Color(0xffadf2d6),
      ClockColor.goo: const Color(0xff5adba8),
      ClockColor.analogTimeBackground: const Color(0xff87e8c8),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffc8fff0),
      ClockColor.weatherBackground: const Color(0xff6ad6b4),
      ClockColor.weatherBackgroundHighlight: const Color(0xffe8fff6),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff6ad6b4),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff9de8d1),
      ClockColor.slidePrimary: const Color(0xff5adba8),
      ClockColor.slideSecondary: const Color(0xff29b989),
      ClockColor.ballPrimary: const Color(0xff5adba8),
      ClockColor.ballSecondary: const Color(0xff1e8c6e),
      ClockColor.petals: const Color(0xff87e8c8),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.thermometerTube: const Color(0xffd8f5e8),
      ClockColor.thermometerMount: const Color(0xff5adba8),
      ClockColor.hourHand: const Color(0xff1e8c6e),
      ClockColor.minuteHand: const Color(0xff0d5544),
      ClockColor.secondHand: const Color(0xff29b989),
      ClockColor.weatherArrow: const Color(0xff1e8c6e),
    }),
  ),
  ClockPalette(
    name: 'Peach',
    isDark: false,
    colors: _light({
      ClockColor.background: const Color(0xffffd8cc),
      ClockColor.goo: const Color(0xffdd9980),
      ClockColor.analogTimeBackground: const Color(0xffffb299),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffffe8dd),
      ClockColor.weatherBackground: const Color(0xffdd9980),
      ClockColor.weatherBackgroundHighlight: const Color(0xfffff0ec),
      ClockColor.thermometerBackgroundPrimary: const Color(0xffdd9980),
      ClockColor.thermometerBackgroundSecondary: const Color(0xffffccbb),
      ClockColor.slidePrimary: const Color(0xffdd9980),
      ClockColor.slideSecondary: const Color(0xffcc6644),
      ClockColor.ballPrimary: const Color(0xffdd9980),
      ClockColor.ballSecondary: const Color(0xffaa4422),
      ClockColor.petals: const Color(0xffffb299),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.thermometerTube: const Color(0xfffae0d8),
      ClockColor.thermometerMount: const Color(0xffdd9980),
      ClockColor.hourHand: const Color(0xffaa4422),
      ClockColor.minuteHand: const Color(0xff772200),
      ClockColor.secondHand: const Color(0xffcc6644),
      ClockColor.weatherArrow: const Color(0xffaa4422),
    }),
  ),
  ClockPalette(
    name: 'Lavender',
    isDark: false,
    colors: _light({
      ClockColor.background: const Color(0xffe8d8ff),
      ClockColor.goo: const Color(0xffb899dd),
      ClockColor.analogTimeBackground: const Color(0xffd4b8f5),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffeeddff),
      ClockColor.weatherBackground: const Color(0xffc4a0e8),
      ClockColor.weatherBackgroundHighlight: const Color(0xfff5eeff),
      ClockColor.thermometerBackgroundPrimary: const Color(0xffc4a0e8),
      ClockColor.thermometerBackgroundSecondary: const Color(0xffddccf5),
      ClockColor.slidePrimary: const Color(0xffb899dd),
      ClockColor.slideSecondary: const Color(0xff8855bb),
      ClockColor.ballPrimary: const Color(0xffb899dd),
      ClockColor.ballSecondary: const Color(0xff6633aa),
      ClockColor.petals: const Color(0xffd4b8f5),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.thermometerTube: const Color(0xffeae4ff),
      ClockColor.thermometerMount: const Color(0xffb899dd),
      ClockColor.hourHand: const Color(0xff6633aa),
      ClockColor.minuteHand: const Color(0xff441188),
      ClockColor.secondHand: const Color(0xff8855bb),
      ClockColor.weatherArrow: const Color(0xff6633aa),
    }),
  ),
];
