import 'components/style/palette.dart';
import 'package:flutter/material.dart';

class ClockPalette {
  final String name;
  final bool isDark;
  final Map<ClockColor, Color> colors;
  const ClockPalette({
    required this.name,
    required this.isDark,
    required this.colors,
  });
}

Map<ClockColor, Color> _build(bool dark, Map<ClockColor, Color> overrides) {
  final result = Map.of(Palette.base);
  result.addAll(dark ? Palette.dark : Palette.light);
  result.addAll(overrides);
  return result;
}

final List<ClockPalette> allClockPalettes = [
  // ── Dark ──────────────────────────────────────────────────────────────────
  ClockPalette(
    name: 'Vibrant Dark',
    isDark: true,
    colors: _build(true, Map.of(Palette.vibrantDark)),
  ),
  ClockPalette(
    name: 'Subtle Dark',
    isDark: true,
    colors: _build(true, Map.of(Palette.subtleDark)),
  ),
  ClockPalette(
    name: 'Neon Noir',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff000014),
      ClockColor.goo: const Color(0xff000028),
      ClockColor.analogTimeBackground: const Color(0xff003344),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff006688),
      ClockColor.weatherBackground: const Color(0xff001133),
      ClockColor.weatherBackgroundHighlight: const Color(0xff002266),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff001122),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff000a14),
      ClockColor.ballPrimary: const Color(0xff00ffcc),
      ClockColor.ballSecondary: const Color(0xff007755),
      ClockColor.slidePrimary: const Color(0xff003344),
      ClockColor.slideSecondary: const Color(0xff001122),
      ClockColor.petals: const Color(0xff00ddaa),
      ClockColor.petalsHighlight: const Color(0xff00ffcc),
      ClockColor.hourHand: const Color(0xff00ffcc),
      ClockColor.minuteHand: const Color(0xff00eebb),
      ClockColor.secondHand: const Color(0xff00ffff),
      ClockColor.weatherArrow: const Color(0xff00ffcc),
      ClockColor.digitalTimeText: const Color(0xff00ffcc),
      ClockColor.thermometerMount: const Color(0xff004433),
    }),
  ),
  ClockPalette(
    name: 'Crimson Night',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff0e0000),
      ClockColor.goo: const Color(0xff1a0000),
      ClockColor.analogTimeBackground: const Color(0xff5c0011),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff8b0020),
      ClockColor.weatherBackground: const Color(0xff3d0008),
      ClockColor.weatherBackgroundHighlight: const Color(0xff6b0014),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff2d0005),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff140000),
      ClockColor.ballPrimary: const Color(0xffcc2233),
      ClockColor.ballSecondary: const Color(0xff440008),
      ClockColor.slidePrimary: const Color(0xff440008),
      ClockColor.slideSecondary: const Color(0xff220004),
      ClockColor.petals: const Color(0xffdd1133),
      ClockColor.petalsHighlight: const Color(0xffff3355),
      ClockColor.hourHand: const Color(0xffff4455),
      ClockColor.minuteHand: const Color(0xffffaabb),
      ClockColor.secondHand: const Color(0xffff0022),
      ClockColor.weatherArrow: const Color(0xffff6677),
      ClockColor.digitalTimeText: const Color(0xffff9999),
      ClockColor.thermometerMount: const Color(0xff550011),
    }),
  ),
  ClockPalette(
    name: 'Deep Ocean',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff00070f),
      ClockColor.goo: const Color(0xff000d1a),
      ClockColor.analogTimeBackground: const Color(0xff002244),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff003d77),
      ClockColor.weatherBackground: const Color(0xff001833),
      ClockColor.weatherBackgroundHighlight: const Color(0xff002d5c),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff001122),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff000a14),
      ClockColor.ballPrimary: const Color(0xff1a7aff),
      ClockColor.ballSecondary: const Color(0xff003388),
      ClockColor.slidePrimary: const Color(0xff002244),
      ClockColor.slideSecondary: const Color(0xff001122),
      ClockColor.petals: const Color(0xff2266dd),
      ClockColor.petalsHighlight: const Color(0xff55aaff),
      ClockColor.hourHand: const Color(0xff88ccff),
      ClockColor.minuteHand: const Color(0xffaaddff),
      ClockColor.secondHand: const Color(0xff55bbff),
      ClockColor.weatherArrow: const Color(0xff66aaee),
      ClockColor.digitalTimeText: const Color(0xff99ddff),
      ClockColor.thermometerMount: const Color(0xff004466),
    }),
  ),
  ClockPalette(
    name: 'Forest Night',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff010a01),
      ClockColor.goo: const Color(0xff021202),
      ClockColor.analogTimeBackground: const Color(0xff083318),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff0d5528),
      ClockColor.weatherBackground: const Color(0xff052211),
      ClockColor.weatherBackgroundHighlight: const Color(0xff0a3d1f),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff031a0b),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff010d05),
      ClockColor.ballPrimary: const Color(0xff22aa44),
      ClockColor.ballSecondary: const Color(0xff0a4418),
      ClockColor.slidePrimary: const Color(0xff083318),
      ClockColor.slideSecondary: const Color(0xff031a0b),
      ClockColor.petals: const Color(0xff33bb55),
      ClockColor.petalsHighlight: const Color(0xff55dd77),
      ClockColor.hourHand: const Color(0xff77dd99),
      ClockColor.minuteHand: const Color(0xff99eebb),
      ClockColor.secondHand: const Color(0xff44cc66),
      ClockColor.weatherArrow: const Color(0xff66cc88),
      ClockColor.digitalTimeText: const Color(0xffaaffcc),
      ClockColor.thermometerMount: const Color(0xff115522),
    }),
  ),
  ClockPalette(
    name: 'Amber Dusk',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff0d0800),
      ClockColor.goo: const Color(0xff1a1000),
      ClockColor.analogTimeBackground: const Color(0xff443300),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff776600),
      ClockColor.weatherBackground: const Color(0xff332200),
      ClockColor.weatherBackgroundHighlight: const Color(0xff554400),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff221800),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff110c00),
      ClockColor.ballPrimary: const Color(0xffddaa00),
      ClockColor.ballSecondary: const Color(0xff554400),
      ClockColor.slidePrimary: const Color(0xff443300),
      ClockColor.slideSecondary: const Color(0xff221800),
      ClockColor.petals: const Color(0xffeeaa00),
      ClockColor.petalsHighlight: const Color(0xffffcc22),
      ClockColor.hourHand: const Color(0xffffcc44),
      ClockColor.minuteHand: const Color(0xffffe077),
      ClockColor.secondHand: const Color(0xffffaa00),
      ClockColor.weatherArrow: const Color(0xffffcc55),
      ClockColor.digitalTimeText: const Color(0xffffeeaa),
      ClockColor.thermometerMount: const Color(0xff665500),
    }),
  ),
  ClockPalette(
    name: 'Aurora',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff010010),
      ClockColor.goo: const Color(0xff030022),
      ClockColor.analogTimeBackground: const Color(0xff0a2244),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff003355),
      ClockColor.weatherBackground: const Color(0xff061133),
      ClockColor.weatherBackgroundHighlight: const Color(0xff0a2244),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff050a22),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff020511),
      ClockColor.ballPrimary: const Color(0xff44ffaa),
      ClockColor.ballSecondary: const Color(0xff115522),
      ClockColor.slidePrimary: const Color(0xff221155),
      ClockColor.slideSecondary: const Color(0xff110a33),
      ClockColor.petals: const Color(0xff55ddff),
      ClockColor.petalsHighlight: const Color(0xff88eecc),
      ClockColor.hourHand: const Color(0xff88ffdd),
      ClockColor.minuteHand: const Color(0xffbbffee),
      ClockColor.secondHand: const Color(0xff44eedd),
      ClockColor.weatherArrow: const Color(0xff66ffcc),
      ClockColor.digitalTimeText: const Color(0xff99ffee),
      ClockColor.thermometerMount: const Color(0xff224455),
    }),
  ),
  ClockPalette(
    name: 'Rose Gold',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff0d0007),
      ClockColor.goo: const Color(0xff1a000e),
      ClockColor.analogTimeBackground: const Color(0xff441122),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff772244),
      ClockColor.weatherBackground: const Color(0xff330a17),
      ClockColor.weatherBackgroundHighlight: const Color(0xff551a2e),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff220814),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff11040a),
      ClockColor.ballPrimary: const Color(0xffdd6688),
      ClockColor.ballSecondary: const Color(0xff882244),
      ClockColor.slidePrimary: const Color(0xff441122),
      ClockColor.slideSecondary: const Color(0xff220810),
      ClockColor.petals: const Color(0xffee88aa),
      ClockColor.petalsHighlight: const Color(0xffffaabb),
      ClockColor.hourHand: const Color(0xffffbbcc),
      ClockColor.minuteHand: const Color(0xffffd4dd),
      ClockColor.secondHand: const Color(0xffff99aa),
      ClockColor.weatherArrow: const Color(0xffffaacc),
      ClockColor.digitalTimeText: const Color(0xffffddee),
      ClockColor.thermometerMount: const Color(0xff662233),
    }),
  ),
  ClockPalette(
    name: 'Slate',
    isDark: true,
    colors: _build(true, {
      ClockColor.background: const Color(0xff07090d),
      ClockColor.goo: const Color(0xff0d1119),
      ClockColor.analogTimeBackground: const Color(0xff1f2d3d),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xff304555),
      ClockColor.weatherBackground: const Color(0xff182130),
      ClockColor.weatherBackgroundHighlight: const Color(0xff253346),
      ClockColor.thermometerBackgroundPrimary: const Color(0xff121a24),
      ClockColor.thermometerBackgroundSecondary: const Color(0xff090e14),
      ClockColor.ballPrimary: const Color(0xff6699bb),
      ClockColor.ballSecondary: const Color(0xff1e3348),
      ClockColor.slidePrimary: const Color(0xff1e2c3c),
      ClockColor.slideSecondary: const Color(0xff0f1820),
      ClockColor.petals: const Color(0xff7799aa),
      ClockColor.petalsHighlight: const Color(0xff99bbcc),
      ClockColor.hourHand: const Color(0xffaaccdd),
      ClockColor.minuteHand: const Color(0xffcce0ee),
      ClockColor.secondHand: const Color(0xff88bbcc),
      ClockColor.weatherArrow: const Color(0xff99ccdd),
      ClockColor.digitalTimeText: const Color(0xffbbddee),
      ClockColor.thermometerMount: const Color(0xff334455),
    }),
  ),
  // ── Light ─────────────────────────────────────────────────────────────────
  ClockPalette(
    name: 'Vibrant Light',
    isDark: false,
    colors: _build(false, Map.of(Palette.vibrantLight)),
  ),
  ClockPalette(
    name: 'Subtle Light',
    isDark: false,
    colors: _build(false, Map.of(Palette.subtleLight)),
  ),
  ClockPalette(
    name: 'Sky Blue',
    isDark: false,
    colors: _build(false, {
      ClockColor.background: const Color(0xffe8f4fd),
      ClockColor.goo: const Color(0xffa8d4f5),
      ClockColor.analogTimeBackground: const Color(0xffd0e8f8),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffffffff),
      ClockColor.weatherBackground: const Color(0xffc0ddf0),
      ClockColor.weatherBackgroundHighlight: const Color(0xfff0f8ff),
      ClockColor.thermometerBackgroundPrimary: const Color(0xffc8e0f5),
      ClockColor.thermometerBackgroundSecondary: const Color(0xffe8f4fd),
      ClockColor.ballPrimary: const Color(0xff3399cc),
      ClockColor.ballSecondary: const Color(0xff004488),
      ClockColor.slidePrimary: const Color(0xff5588aa),
      ClockColor.slideSecondary: const Color(0xff336688),
      ClockColor.petals: const Color(0xff2277bb),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.hourHand: const Color(0xff003366),
      ClockColor.minuteHand: const Color(0xff000000),
      ClockColor.secondHand: const Color(0xff002255),
      ClockColor.weatherArrow: const Color(0xff002244),
      ClockColor.digitalTimeText: const Color(0xff002244),
      ClockColor.thermometerMount: const Color(0xff447799),
      ClockColor.thermometerTube: const Color(0xffd8eef9),
    }),
  ),
  ClockPalette(
    name: 'Mint',
    isDark: false,
    colors: _build(false, {
      ClockColor.background: const Color(0xffe8f7f0),
      ClockColor.goo: const Color(0xffaaddc0),
      ClockColor.analogTimeBackground: const Color(0xffc8eedd),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffffffff),
      ClockColor.weatherBackground: const Color(0xffb8e8cc),
      ClockColor.weatherBackgroundHighlight: const Color(0xfff0fdf6),
      ClockColor.thermometerBackgroundPrimary: const Color(0xffd0f0e0),
      ClockColor.thermometerBackgroundSecondary: const Color(0xffe8f7f0),
      ClockColor.ballPrimary: const Color(0xff22aa66),
      ClockColor.ballSecondary: const Color(0xff005533),
      ClockColor.slidePrimary: const Color(0xff44997a),
      ClockColor.slideSecondary: const Color(0xff226644),
      ClockColor.petals: const Color(0xff118855),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.hourHand: const Color(0xff003322),
      ClockColor.minuteHand: const Color(0xff000000),
      ClockColor.secondHand: const Color(0xff002211),
      ClockColor.weatherArrow: const Color(0xff004422),
      ClockColor.digitalTimeText: const Color(0xff004433),
      ClockColor.thermometerMount: const Color(0xff44885a),
      ClockColor.thermometerTube: const Color(0xffd8f5e8),
    }),
  ),
  ClockPalette(
    name: 'Peach',
    isDark: false,
    colors: _build(false, {
      ClockColor.background: const Color(0xfffff3ee),
      ClockColor.goo: const Color(0xfff5c4b0),
      ClockColor.analogTimeBackground: const Color(0xfffdddd5),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffffffff),
      ClockColor.weatherBackground: const Color(0xfffcd5cc),
      ClockColor.weatherBackgroundHighlight: const Color(0xfffffaf8),
      ClockColor.thermometerBackgroundPrimary: const Color(0xfffde0d8),
      ClockColor.thermometerBackgroundSecondary: const Color(0xfffff3ee),
      ClockColor.ballPrimary: const Color(0xffdd6644),
      ClockColor.ballSecondary: const Color(0xff882211),
      ClockColor.slidePrimary: const Color(0xffcc7755),
      ClockColor.slideSecondary: const Color(0xffaa5533),
      ClockColor.petals: const Color(0xffcc5533),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.hourHand: const Color(0xff441100),
      ClockColor.minuteHand: const Color(0xff000000),
      ClockColor.secondHand: const Color(0xff330d00),
      ClockColor.weatherArrow: const Color(0xff552211),
      ClockColor.digitalTimeText: const Color(0xff441100),
      ClockColor.thermometerMount: const Color(0xffaa6644),
      ClockColor.thermometerTube: const Color(0xfffae0d8),
    }),
  ),
  ClockPalette(
    name: 'Lavender',
    isDark: false,
    colors: _build(false, {
      ClockColor.background: const Color(0xfff4f0ff),
      ClockColor.goo: const Color(0xffcdbfff),
      ClockColor.analogTimeBackground: const Color(0xffe8e0ff),
      ClockColor.analogTimeBackgroundHighlight: const Color(0xffffffff),
      ClockColor.weatherBackground: const Color(0xffe0d8ff),
      ClockColor.weatherBackgroundHighlight: const Color(0xfffff9ff),
      ClockColor.thermometerBackgroundPrimary: const Color(0xffeae4ff),
      ClockColor.thermometerBackgroundSecondary: const Color(0xfff4f0ff),
      ClockColor.ballPrimary: const Color(0xff7755cc),
      ClockColor.ballSecondary: const Color(0xff330088),
      ClockColor.slidePrimary: const Color(0xff997acc),
      ClockColor.slideSecondary: const Color(0xff774499),
      ClockColor.petals: const Color(0xff6644bb),
      ClockColor.petalsHighlight: const Color(0xffffffff),
      ClockColor.hourHand: const Color(0xff220055),
      ClockColor.minuteHand: const Color(0xff000000),
      ClockColor.secondHand: const Color(0xff3300aa),
      ClockColor.weatherArrow: const Color(0xff330066),
      ClockColor.digitalTimeText: const Color(0xff440077),
      ClockColor.thermometerMount: const Color(0xff886699),
      ClockColor.thermometerTube: const Color(0xffeae4ff),
    }),
  ),
];
