// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/creativecreatorormaybenot/clock',
  orientation: Orientation.landscape,
  description: 'A visually striking, fully custom‑drawn clock UI built with Flutter Canvas.',
);
