// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Canvas Clock',
  githubRepoUrl: 'https://github.com/creativecreatorormaybenot/clock',
  orientation: Orientation.landscape,
  description: 'Physics-based canvas clock with animated ball and weather',
);
