// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterWebXRThreeJS',
  githubRepoUrl: 'https://github.com/rodydavis/FlutterWebXRThreeJS',
  orientation: Orientation.landscape,
  description: 'A Flutter web demo showcasing a 3D scene with audio using ThreeJS.',
);
