// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Pendulum Clock',
  githubRepoUrl: 'https://github.com/HassanDev1/pendulum_clock',
  orientation: Orientation.landscape,
  description: 'Animated pendulum clock showing current time.',
);
