// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Tetris',
  githubRepoUrl: 'https://github.com/boyan01/flutter-tetris',
  orientation: Orientation.landscape,
  description: 'A Flutter‑based Tetris game with smooth animations and responsive UI.',
);
