// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clocks',
  githubRepoUrl: 'https://github.com/raycardillo/flutter_clocks',
  orientation: Orientation.landscape,
  description: 'A collection of beautiful standalone clock UI experiences for Flutter.',
);
