// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App',
  githubRepoUrl: 'https://github.com/oguzsh/flutter_clock_app',
  orientation: Orientation.landscape,
  description: 'A beautiful digital clock with weather and location info.',
);
