// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flip Clock',
  githubRepoUrl: 'https://github.com/aidevjoe/Flip-Clock',
  orientation: Orientation.landscape,
  description: 'Animated flip‑clock widget with customizable themes.',
);
