// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App UI',
  githubRepoUrl: 'https://github.com/ashu98s/Flutter-Clock-App-UI',
  orientation: Orientation.landscape,
  description: 'A clean analog clock UI supporting light and dark themes.',
);
