// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Turi',
  githubRepoUrl: 'https://github.com/renancaraujo/turi',
  orientation: Orientation.landscape,
  description: 'A stunning shader‑driven game built with Flame, showcasing animated graphics in one screen.',
);
