// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Digital Clock',
  githubRepoUrl: 'https://github.com/VikasPandey121/Digital-Clock',
  orientation: Orientation.portrait,
  description: 'Animated digital clock UI in Flutter.',
);
