// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Bike Clock',
  githubRepoUrl: 'https://github.com/dshukertjr/bike_clock',
  orientation: Orientation.landscape,
  description: 'A visually appealing animated clock face built with Flutter.',
);
