// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Dark Light App',
  githubRepoUrl: 'https://github.com/zendy199x/Flutter-Analog-Clock-Dark-Light-App',
  orientation: Orientation.landscape,
  description: 'A standalone analog clock with theme switching, suitable for UI showcase.',
);
