// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Stream',
  githubRepoUrl: 'https://github.com/tensor-programming/clock-stream',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with digital overlay, using Provider and CustomPainter.',
);
