// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Onboarding Screen',
  githubRepoUrl: 'https://github.com/danufirdaus/Flutter-Onboarding-Screen',
  orientation: Orientation.portrait,
  description: 'A three‑screen onboarding UI with animated dots and customizable content.',
);
