// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Animated Pandulum Clock',
  githubRepoUrl: 'https://github.com/Shehzaan-Mansuri/Animated-Pandulum-Clock',
  orientation: Orientation.landscape,
  description: 'A simple animated pendulum clock UI with swinging motion.',
);
