// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Running Clock',
  githubRepoUrl: 'https://github.com/Mindinventory/running-clock',
  orientation: Orientation.landscape,
  description: 'Animated digital clock with running animations, dark/light mode, and smooth transitions.',
);
