// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/Alameen688/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A Fibonacci‑based clock with colorful squares and optional weather display.',
);
