// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Paint Redesigned',
  githubRepoUrl: 'https://github.com/maheshj01/Paint-Redesigned',
  orientation: Orientation.landscape,
  description: 'A desktop Flutter paint app with brush, eraser, zoom, and image import.',
);
