// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App',
  githubRepoUrl: 'https://github.com/man-of-mind/Flutter-Clock-App',
  orientation: Orientation.landscape,
  description: 'A simple yet animated analog and digital clock widget.',
);
