// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Momo Sliver Appbar',
  githubRepoUrl: 'https://github.com/iamv4g/flutter-momo-sliver-appbar',
  orientation: Orientation.portrait,
  description: 'A sleek MoMo‑style collapsing toolbar demo with animated cards and balance bar.',
);
