// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Minimalist Clock Flutter',
  githubRepoUrl: 'https://github.com/leonamtv/minimalist-clock-flutter',
  orientation: Orientation.landscape,
  description: 'A minimalist animated clock with rotating custom paint.',
);
