// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Card Flip',
  githubRepoUrl: 'https://github.com/xujiyou/card_flip',
  orientation: Orientation.portrait,
  description: 'A Flutter demo showing a smooth card‑flip carousel with animated text and progress bar.',
);
