// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Countdown Clock',
  githubRepoUrl: 'https://github.com/MattisBrizard/countdown_clock',
  orientation: Orientation.landscape,
  description: 'A beautiful countdown clock face visualizing the remaining time of your day.',
);
