// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/talhakhan1297/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A standalone analog clock widget with dark and light themes.',
);
