// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Animated Digital Clock Flutter',
  githubRepoUrl: 'https://github.com/TechieBlossom/animated_digital_clock_flutter',
  orientation: Orientation.landscape,
  description: 'Animated digital clock with moving dot digits.',
);
