// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock With Flutter',
  githubRepoUrl: 'https://github.com/abdussatter51/Analog_Clock_With_Flutter',
  orientation: Orientation.landscape,
  description: 'A standalone analog clock widget with moving hands drawn via CustomPaint.',
);
