// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/NilsEngelbach/flutter_clock',
  orientation: Orientation.landscape,
  description: 'Retro‑styled digital 7‑segment clock with light/dark themes and weather info.',
);
