// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Design Using Flutter',
  githubRepoUrl: 'https://github.com/Nilupa-Illangarathna/Analog-Clock-Design-using-flutter',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with gradient hands.',
);
