// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Airbnb Passport',
  githubRepoUrl: 'https://github.com/ksokolovskyi/airbnb_passport',
  orientation: null,
  description: 'Airbnb Host Passport UI demo with animated cards and hero transitions.',
);
