// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Cloc',
  githubRepoUrl: 'https://github.com/justkawal/cloc',
  orientation: Orientation.landscape,
  description: 'A grid of 153 animated analog clocks displaying time in digital format.',
);
