// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Calendar',
  githubRepoUrl: 'https://github.com/lohanidamodar/flutter_calendar',
  orientation: Orientation.portrait,
  description: 'Flutter calendar demo',
);
