// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Parallax Scroll',
  githubRepoUrl: 'https://github.com/pawlik92/flutter_parallax_scroll',
  orientation: Orientation.portrait,
  description: 'Parallax scrolling UI demo with animated layers',
);
