// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'SalesApp',
  githubRepoUrl: 'https://github.com/JideGuru/SalesApp',
  orientation: Orientation.portrait,
  description: 'A standalone Flutter sales‑app UI with gradient header and animated cards.',
);
