// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Light Dark Theme',
  githubRepoUrl: 'https://github.com/abuanwar072/Flutter-Analog-Clock-Light-Dark-Theme',
  orientation: Orientation.landscape,
  description: 'A clean analog clock demo with light and dark mode support.',
);
