// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/NPKompleet/Clock',
  orientation: Orientation.landscape,
  description: 'A custom‑styled analog clock with animated hands and optional decorations.',
);
