// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock',
  githubRepoUrl: 'https://github.com/emilysmithson/analog_clock',
  orientation: Orientation.landscape,
  description: 'A mesmerizing animated analog clock with rotating arcs.',
);
