// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Interact Clock',
  githubRepoUrl: 'https://github.com/Vanethos/flutter-interact-clock',
  orientation: Orientation.landscape,
  description: 'Animated clock UI showcasing Flutter\'s animation capabilities.',
);
