// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: '214 Flutter Binary Clock',
  githubRepoUrl: 'https://github.com/fireship-io/214-flutter-binary-clock',
  orientation: Orientation.landscape,
  description: 'A binary clock visualizing time in a sleek, animated layout.',
);
