// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Cherry Clock',
  githubRepoUrl: 'https://github.com/cherry-design/cherry_clock',
  orientation: Orientation.landscape,
  description: 'A single‑screen animated clock with customizable light and dark themes.',
);
