// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/Nomeyho/flutter-clock',
  orientation: Orientation.landscape,
  description: 'A unique clock face where each digit is formed by six animated analog clocks.',
);
