// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock2',
  githubRepoUrl: 'https://github.com/dhananjaysahu79/clock2',
  orientation: Orientation.landscape,
  description: 'A stylish animated clock with dark/light theme toggle.',
);
