// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Web Food App UI',
  githubRepoUrl: 'https://github.com/abuanwar072/Flutter-Web---Food-App-UI',
  orientation: Orientation.landscape,
  description: 'A simple, visually appealing food‑app UI for Flutter Web.',
);
