// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Drawer3d',
  githubRepoUrl: 'https://github.com/papmodern/drawer3d',
  orientation: Orientation.portrait,
  description: 'A 3D sliding drawer animation demo for Flutter.',
);
