// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Agent Clock',
  githubRepoUrl: 'https://github.com/kruegerrobotics/flutter_agent_clock',
  orientation: Orientation.landscape,
  description: 'Animated agent‑based clock visualizing time with particles.',
);
