// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/shashilaheshan/flutter-clock-challenge',
  orientation: Orientation.portrait,
  description: 'A simple animated clock demo for Flutter.',
);
