// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/nosliwmichael/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A lo‑fi inspired clock face with animated hands and background.',
);
