// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Tinder Cards',
  githubRepoUrl: 'https://github.com/Ivaskuu/tinder_cards',
  orientation: Orientation.portrait,
  description: 'A swipeable stack of cards mimicking Tinder\'s UI, with draggable and gesture‑based implementations.',
);
