// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Dino Run',
  githubRepoUrl: 'https://github.com/ufrshubham/dino_run',
  orientation: Orientation.landscape,
  description: 'A colorful infinite side‑scroller game built with Flutter and Flame.',
);
