// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/shakirkasmani/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A bold, animated analog clock with tourbillon mechanism, date, day and weather icons.',
);
