// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App',
  githubRepoUrl: 'https://github.com/SurajLad/Flutter-Clock-App',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with custom painter in a single view.',
);
