// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Workout Clock',
  githubRepoUrl: 'https://github.com/gos-k/flutter_workout_clock',
  orientation: Orientation.landscape,
  description: 'A simple workout clock with a large, updating timer display.',
);
