// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Light Dark Toggle',
  githubRepoUrl: 'https://github.com/shubhamhackz/light_dark_toggle',
  orientation: Orientation.portrait,
  description: 'A beautiful animated toggle switching between light and dark themes.',
);
