// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clocky Mcclockface',
  githubRepoUrl: 'https://github.com/Toglefritz/clocky_mcclockface',
  orientation: Orientation.landscape,
  description: 'A simple yet animated clock with analog and digital faces.',
);
