// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge Barbar',
  githubRepoUrl: 'https://github.com/aednlaxer/flutter-clock-challenge-barbar',
  orientation: Orientation.landscape,
  description: 'Animated BarBar clock face with moving bars, date and weather info.',
);
