// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Fluttering Clock',
  githubRepoUrl: 'https://github.com/Russiarain/fluttering_clock',
  orientation: Orientation.landscape,
  description: 'A visually rich animated clock face with weather‑based themes and wave‑based seconds display.',
);
