// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Ui Challenge Flight Search',
  githubRepoUrl: 'https://github.com/MarcinusX/flutter_ui_challenge_flight_search',
  orientation: Orientation.portrait,
  description: 'A polished, animated flight search screen showcasing custom widgets and transitions.',
);
