// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Hex Clock',
  githubRepoUrl: 'https://github.com/jg-l/flutter-hex-clock',
  orientation: Orientation.landscape,
  description: 'A clock whose background color changes with the current time.',
);
