// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Cloom Clock',
  githubRepoUrl: 'https://github.com/OldMetalmind/cloom_clock',
  orientation: Orientation.portrait,
  description: 'A beautiful animated digital clock demo from the 2020 Flutter Clock Challenge.',
);
