// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClockChallenge',
  githubRepoUrl: 'https://github.com/cookmscott/FlutterClockChallenge',
  orientation: Orientation.landscape,
  description: 'A modern 3D‑style digital clock with smooth animations and dark/light themes.',
);
