// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Linux Analog Clock',
  githubRepoUrl: 'https://github.com/aula-id/linux-analog-clock',
  orientation: Orientation.landscape,
  description: 'A beautiful analog clock widget for Linux.',
);
