// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Jardinains',
  githubRepoUrl: 'https://github.com/retroportalstudio/flutter_jardinains',
  orientation: Orientation.landscape,
  description: 'A standalone, animated Pong‑style game showcasing Flutter UI capabilities.',
);
