// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterAnalogClock',
  githubRepoUrl: 'https://github.com/ouzari/FlutterAnalogClock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock widget demo.',
);
