// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Protfolio Website Flutter Web',
  githubRepoUrl: 'https://github.com/abuanwar072/Protfolio-Website-Flutter-Web',
  orientation: Orientation.landscape,
  description: 'A static Flutter web portfolio with animated sections and custom widgets.',
);
