// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Radial Clock',
  githubRepoUrl: 'https://github.com/IsaTippens/flutter_clock',
  orientation: Orientation.landscape,
  description: 'Animated analogue clock that rotates its hands in real time.',
);
