// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Neumorphism Clock',
  githubRepoUrl: 'https://github.com/gossiks/neumorphism_clock',
  orientation: Orientation.landscape,
  description: 'Neumorphic digital clock with soft UI and animated hands.',
);
