// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Awesome Clock',
  githubRepoUrl: 'https://github.com/realpacific/awesome_clock',
  orientation: Orientation.landscape,
  description: 'Animated clock with custom visual design for the FlutterClock challenge.',
);
