// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Dots Clock',
  githubRepoUrl: 'https://github.com/kainsteffen/dots-clock',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock with noise‑driven dot patterns.',
);
