// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Lava Clock',
  githubRepoUrl: 'https://github.com/jamesblasco/flutter_lava_clock',
  orientation: Orientation.landscape,
  description: 'A molten‑lava styled animated clock for the Flutter Clock Challenge.',
);
