// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Bounce Game',
  githubRepoUrl: 'https://github.com/Shadow60539/bounce_game',
  orientation: Orientation.landscape,
  description: 'A simple yet lively bounce game demo in Flutter.',
);
