// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Long Shadow Clock',
  githubRepoUrl: 'https://github.com/ianko/Long-Shadow-Clock',
  orientation: Orientation.landscape,
  description: 'A vibrant long‑shadow clock with animated digits and rainbow effects.',
);
