// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Anuj Clock',
  githubRepoUrl: 'https://github.com/myselfanuj/Anuj_Clock',
  orientation: Orientation.portrait,
  description: 'A simple animated digital clock with a swinging effect.',
);
