// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flutterclock',
  githubRepoUrl: 'https://github.com/mitesh77/flutterclock',
  orientation: Orientation.landscape,
  description: 'Animated digital clock demo with smooth transitions.',
);
