// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/luciferro01/Clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock widget with custom paint and second‑hand updates.',
);
