// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Signature',
  githubRepoUrl: 'https://github.com/vemarav/signature',
  orientation: Orientation.portrait,
  description: 'A simple signature drawing app that lets you sketch and save PNG images.',
);
