// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock',
  githubRepoUrl: 'https://github.com/abstrxtInfinity/Analog-Clock',
  orientation: Orientation.landscape,
  description: 'A beautiful analog clock with light and dark themes.',
);
