// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/cruzelx/flutter_clock_challenge',
  orientation: Orientation.landscape,
  description: 'A simple, animated digital clock demo.',
);
