// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Doctor Appointment Flutter',
  githubRepoUrl: 'https://github.com/PavieOlivier/doctor-appointment-flutter',
  orientation: Orientation.portrait,
  description: 'A responsive doctor appointment UI demo for Flutter.',
);
