// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Helg9000',
  githubRepoUrl: 'https://github.com/HelgeWieding/helg9000',
  orientation: Orientation.landscape,
  description: 'Animated clock showing weather and temperature, drawn entirely in code.',
);
