// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Dartbinaryclock',
  githubRepoUrl: 'https://github.com/daftspaniel/dartbinaryclock',
  orientation: Orientation.landscape,
  description: 'A colourful binary clock visualised in Dart.',
);
