// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Time Shift',
  githubRepoUrl: 'https://github.com/shorebirdtech/time_shift',
  orientation: Orientation.landscape,
  description: 'A full-screen particle clock demo with optional code‑push updates.',
);
