// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/vukan-markovic/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A standalone Flutter clock demo with animated hands and custom drawing.',
);
