// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Riveo Page Curl',
  githubRepoUrl: 'https://github.com/Rahiche/riveo_page_curl',
  orientation: null,
  description: 'Showcases a beautiful page‑curl effect for deleting cards in Flutter.',
);
