// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Algorithms Visualization',
  githubRepoUrl: 'https://github.com/igniti0n/flutter_algorithms_visualization',
  orientation: Orientation.landscape,
  description: 'Animated path‑finding visualizer with Dijkstra, A* and maze generation.',
);
