// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Home Widget Vignette',
  githubRepoUrl: 'https://github.com/gskinnerTeam/flutter-home-widget-vignette',
  orientation: null,
  description: 'Animated counter widget',
);
