// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Furniture App Ui Challenge',
  githubRepoUrl: 'https://github.com/Dinesh-Sowndar/flutter_furniture_app_ui_challenge',
  orientation: Orientation.portrait,
  description: 'A polished furniture app home screen with animated category and product cards.',
);
