// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterUniverseClock',
  githubRepoUrl: 'https://github.com/byronap120/FlutterUniverseClock',
  orientation: Orientation.portrait,
  description: 'A digital clock floating in a universe with animated stars and a black hole.',
);
