// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Expert Flutter Cv App',
  githubRepoUrl: 'https://github.com/amirahmadadibi/expert_flutter_cv_app',
  orientation: Orientation.portrait,
  description: 'A beautiful Flutter CV app with a stunning design and animations.',
);
