// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Page Transformer',
  githubRepoUrl: 'https://github.com/roughike/page-transformer',
  orientation: Orientation.portrait,
  description: 'A demo of animated PageView transformations with parallax effects.',
);
