// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Goon Clock',
  githubRepoUrl: 'https://github.com/Mastagoon/goon-clock',
  orientation: Orientation.landscape,
  description: 'A simple animated analog clock rendered with custom painting.',
);
