// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Painter',
  githubRepoUrl: 'https://github.com/cscoderr/flutter_clock_painter',
  orientation: Orientation.landscape,
  description: 'A standalone Flutter app showcasing a custom‑paint clock with animated hands.',
);
