// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Mflutter Clock',
  githubRepoUrl: 'https://github.com/mannprerak2/mflutter_clock',
  orientation: Orientation.landscape,
  description: 'Animated clock UI showcasing creative Flutter visuals.',
);
