// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flip View',
  githubRepoUrl: 'https://github.com/shubhamhackz/flip_view',
  orientation: Orientation.portrait,
  description: 'A standalone flip‑card view showcasing animated profile cards.',
);
