// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Custom Carousel',
  githubRepoUrl: 'https://github.com/gskinnerTeam/flutter_custom_carousel',
  orientation: Orientation.landscape,
  description: 'Custom animated carousel',
);
