// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterMayaClock',
  githubRepoUrl: 'https://github.com/robertodevs/FlutterMayaClock',
  orientation: Orientation.landscape,
  description: 'A standalone clock displaying Maya numerals in a creative UI.',
);
