// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'TheGorgeousLogin',
  githubRepoUrl: 'https://github.com/huextrat/TheGorgeousLogin',
  orientation: Orientation.portrait,
  description: 'A gorgeous, animated login page demo for Flutter.',
);
