// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Digital Clock',
  githubRepoUrl: 'https://github.com/Gulshid/Digital-Clock',
  orientation: Orientation.landscape,
  description: 'A simple standalone digital and analog clock widget.',
);
