// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Simple Clock Ui',
  githubRepoUrl: 'https://github.com/akshay512/simple_clock_ui',
  orientation: Orientation.landscape,
  description: 'A sleek animated clock UI for Flutter.',
);
