// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Spending Tracker',
  githubRepoUrl: 'https://github.com/Aldo111/Flutter-Spending-Tracker',
  orientation: Orientation.portrait,
  description: 'A minimal, visually polished spending tracker home screen demo.',
);
