// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/maryx/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A beautiful Flutter Clock demo with animated analog and digital faces.',
);
