// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Animation',
  githubRepoUrl: 'https://github.com/renuvkelkar/clock_animation',
  orientation: Orientation.portrait,
  description: 'Animated digital clock with smooth swinging effect.',
);
