// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Scifi Ui',
  githubRepoUrl: 'https://github.com/filiph/scifi_ui',
  orientation: null,
  description: 'A standalone Flutter demo showcasing animated sci‑fi UI elements.',
);
