// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Single Product Page UI',
  githubRepoUrl: 'https://github.com/devefy/Flutter-Single-Product-Page-UI',
  orientation: Orientation.portrait,
  description: 'A visually appealing single‑product page UI demo for Flutter.',
);
