// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Pomodoro Clock Flutter',
  githubRepoUrl: 'https://github.com/Gustaviusss/pomodoro_clock_flutter',
  orientation: Orientation.portrait,
  description: 'A simple Pomodoro timer with animated circular progress and start/stop button.',
);
