// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Simple Clock Flutter',
  githubRepoUrl: 'https://github.com/Adnan9011/simple_clock_flutter',
  orientation: Orientation.landscape,
  description: 'A simple analog and digital clock widget demo.',
);
