// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'CustomClock',
  githubRepoUrl: 'https://github.com/anilgsharma900/CustomClock',
  orientation: Orientation.landscape,
  description: 'A standalone animated analog clock built with CustomPainter.',
);
