// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock',
  githubRepoUrl: 'https://github.com/saparkhid/flutter-analog-clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock widget with rotating hands.',
);
