// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterProgressButton',
  githubRepoUrl: 'https://github.com/IhorKlimov/FlutterProgressButton',
  orientation: null,
  description: 'A circular reveal progress button animation demo.',
);
