// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flipper Clock',
  githubRepoUrl: 'https://github.com/HSCOGT/Flipper-Clock',
  orientation: Orientation.landscape,
  description: 'A flipping‑tile clock with vibrant animations.',
);
