// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Galaxy Clock',
  githubRepoUrl: 'https://github.com/Nismaiel/galaxy_clock',
  orientation: Orientation.landscape,
  description: 'Animated digital‑analog galaxy clock for a smart display.',
);
