// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Circle Clock',
  githubRepoUrl: 'https://github.com/oli06/circle_clock',
  orientation: Orientation.landscape,
  description: 'A beautiful animated circular clock for the Flutter Clock Challenge.',
);
