// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Nested Tabs',
  githubRepoUrl: 'https://github.com/whatsupcoders/Flutter-Nested-Tabs',
  orientation: Orientation.portrait,
  description: 'Demo of nested tab navigation with custom icons and colors.',
);
