// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Review Page Interaction',
  githubRepoUrl: 'https://github.com/Mindinventory/Flutter-review-page-interaction',
  orientation: Orientation.portrait,
  description: 'A standalone Flutter demo showcasing an animated review page with arc menu and expressive smiley.',
);
