// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Login Page 3',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-Login-Page-3',
  orientation: Orientation.portrait,
  description: 'Animated gradient login page with fade‑in text and input fields.',
);
