// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Inspiration App Ui',
  githubRepoUrl: 'https://github.com/afgprogrammer/flutter-inspiration-app-ui',
  orientation: Orientation.portrait,
  description: 'A standalone Flutter UI showcase featuring a styled list view on a single screen.',
);
