// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Pacman Clock',
  githubRepoUrl: 'https://github.com/alohadance265/pacman_clock',
  orientation: Orientation.landscape,
  description: 'A playful Pac‑Man digital clock with moving ghosts and animated digits.',
);
