// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Watchsteroids',
  githubRepoUrl: 'https://github.com/renancaraujo/watchsteroids',
  orientation: Orientation.landscape,
  description: 'Watchsteroids – an Asteroids‑style game for WearOS with animated graphics.',
);
