// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Smart Clock',
  githubRepoUrl: 'https://github.com/jhomlala/smart-clock',
  orientation: Orientation.landscape,
  description: 'A visually appealing animated clock widget for Flutter.',
);
