// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Humanbeans Clock',
  githubRepoUrl: 'https://github.com/brestnichki/humanbeans-clock',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock where a rare bird visits once a day.',
);
