// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Insta Assets Picker',
  githubRepoUrl: 'https://github.com/LeGoffMael/insta_assets_picker',
  orientation: Orientation.portrait,
  description: 'A beautiful, Instagram-style image and video picker with multi-selection, cropping, and aspect ratio controls.',
);
