// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: '3DBall',
  githubRepoUrl: 'https://github.com/al4fun/3DBall',
  orientation: null,
  description: 'A rotating 3D ball with text labels that demonstrates perspective and animation in a single widget.',
);
