// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterDragCard',
  githubRepoUrl: 'https://github.com/HitenDev/FlutterDragCard',
  orientation: Orientation.portrait,
  description: 'A beautiful drag‑card interaction demo replicating the Jike app exploration page.',
);
