// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Design Collection',
  githubRepoUrl: 'https://github.com/martinoyovo/flutter-design-collection',
  orientation: Orientation.portrait,
  description: 'A collection of standalone Flutter UI animations and kits, each runnable as a single-screen demo.',
);
