// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flippable Box',
  githubRepoUrl: 'https://github.com/gskinnerTeam/flutter-flippable-box',
  orientation: null,
  description: 'Flippable box widget',
);
