// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'ClockApp Flutter',
  githubRepoUrl: 'https://github.com/romanlytcinchuk012/ClockApp-Flutter',
  orientation: Orientation.landscape,
  description: 'Animated clock UI demo built with Flutter.',
);
