// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/chinster99/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A hybrid analog/digital clock with orbiting satellites, weather, date, and location info.',
);
