// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Login Page Design',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-Login-Page-Design',
  orientation: Orientation.portrait,
  description: 'Animated single‑screen login UI with smooth transitions.',
);
