// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Sample',
  githubRepoUrl: 'https://github.com/RayOkaah/flutter_clock_sample',
  orientation: Orientation.landscape,
  description: 'Beautiful analog and digital clock faces built with Flutter.',
);
