// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Scenery FlutterClock',
  githubRepoUrl: 'https://github.com/Dwite/Scenery-FlutterClock',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock that visualizes time, weather, and day‑night cycles.',
);
