// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Parallax Effect',
  githubRepoUrl: 'https://github.com/abuanwar072/Flutter-Parallax-Effect',
  orientation: Orientation.portrait,
  description: 'A single‑screen parallax scroll effect demo using PageView and animated bottom sheet.',
);
