// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'AeroClock',
  githubRepoUrl: 'https://github.com/treejeig/AeroClock',
  orientation: Orientation.landscape,
  description: 'A customizable animated clock with radar second hand and date display.',
);
