// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Sand Clock Animation Flutter',
  githubRepoUrl: 'https://github.com/Naighu/Sand-Clock-Animation-Flutter',
  orientation: Orientation.landscape,
  description: 'Animated sand hour‑glass visual demo in Flutter.',
);
