// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Particle Clock',
  githubRepoUrl: 'https://github.com/miickel/flutter_particle_clock',
  orientation: null,
  description: 'Animated particle clock',
);
