// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Particle Clock',
  githubRepoUrl: 'https://github.com/miickel/flutter_particle_clock',
  orientation: Orientation.landscape,
  description: 'Animated particle clock',
);
