// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Star Clock',
  githubRepoUrl: 'https://github.com/ciriousjoker/star_clock',
  orientation: Orientation.landscape,
  description: 'A visually rich animated clock with day/night cycles and weather effects.',
);
