// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Zoom Analog Clock',
  githubRepoUrl: 'https://github.com/ThomasEcalle/zoom_analog_clock',
  orientation: Orientation.landscape,
  description: 'A hypnotic zoomed analog clock with light/dark themes.',
);
