// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Sunset Reflections Clock',
  githubRepoUrl: 'https://github.com/vmorilla/sunset_reflections_clock',
  orientation: Orientation.landscape,
  description: 'A novelty clock with reflective sunset view and moon/sun positions.',
);
