// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'SimpleClock',
  githubRepoUrl: 'https://github.com/kevin-zhan/SimpleClock',
  orientation: Orientation.landscape,
  description: 'A minimalist, animated digital clock that fills the screen with large numbers.',
);
