// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Scene Example',
  githubRepoUrl: 'https://github.com/bdero/flutter-scene-example',
  orientation: Orientation.landscape,
  description: 'A standalone 3D game demo built with Flutter Scene, featuring animated gameplay and rich assets.',
);
