// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/Diaga/flutter-clock-challenge',
  orientation: Orientation.landscape,
  description: 'A futuristic animated digital clock demo for Flutter.',
);
