// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Ui Challenge Filter Menu',
  githubRepoUrl: 'https://github.com/MarcinusX/flutter_ui_challenge_filter_menu',
  orientation: Orientation.portrait,
  description: 'A visually rich filter menu with animated FAB and custom clipping.',
);
