// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/JesperBellenbaum/flutterClock',
  orientation: Orientation.landscape,
  description: 'Animated analog and digital clock for smart displays',
);
