// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Animal Clock',
  githubRepoUrl: 'https://github.com/seiwonlee/animal_clock',
  orientation: Orientation.landscape,
  description: 'Animated animal clock with lively Flare characters reacting to time changes.',
);
