// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Teddy SignIn',
  githubRepoUrl: 'https://github.com/GJJ2019/Flutter-Teddy-SignIn',
  orientation: Orientation.portrait,
  description: 'A cute Teddy‑animated sign‑in page with validation and loading effects.',
);
