// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'GridView Example UI',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-GridView-Example-UI',
  orientation: Orientation.landscape,
  description: 'A self‑contained, visually appealing GridView showcase for Flutter.',
);
