// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Reflectly Flutter App',
  githubRepoUrl: 'https://github.com/sagarshende23/Reflectly-Flutter-App',
  orientation: Orientation.portrait,
  description: 'A visually rich, animated login screen inspired by Reflectly.',
);
