// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Packinstall',
  githubRepoUrl: 'https://github.com/Kudec61/analog_clock_packinstall',
  orientation: Orientation.landscape,
  description: 'A simple analog clock UI demo with custom hour markers.',
);
