// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'App Intro With Indicator',
  githubRepoUrl: 'https://github.com/afgprogrammer/Flutter-App-Intro-With-Indicator',
  orientation: Orientation.portrait,
  description: 'Animated multi‑page app intro UI with custom colors and text.',
);
