// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/StuartApp/Flutter-clock-challenge',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock face with dynamic weather and night mode.',
);
