// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Dsc Flutter Clock',
  githubRepoUrl: 'https://github.com/filleduchaos/dsc_flutter_clock',
  orientation: Orientation.landscape,
  description: 'Animated clock UI with theme switching, perfect for a showcase.',
);
