// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/Shady-Selim/flutter_clock',
  orientation: Orientation.landscape,
  description: 'Animated Flutter Clock UI with analog and digital styles.',
);
