// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Drawing Board',
  githubRepoUrl: 'https://github.com/JideGuru/flutter_drawing_board',
  orientation: null,
  description: 'A simple drawing board app with canvas, shapes, eraser, undo/redo, and export.',
);
