// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/arleyhr/flutter_clock_challenge',
  orientation: Orientation.landscape,
  description: 'Animated Flutter Clock demo with custom visual style.',
);
