// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Trex Flame',
  githubRepoUrl: 'https://github.com/bluefireteam/trex-flame',
  orientation: Orientation.landscape,
  description: 'A Flutter‑Flame recreation of the Chrome T‑Rex endless runner.',
);
