// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Qlocktwo',
  githubRepoUrl: 'https://github.com/BirjuVachhani/qlocktwo',
  orientation: Orientation.landscape,
  description: 'A stylized QLOCKTWO clock displaying time with a 110‑letter grid.',
);
