// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Video Editor',
  githubRepoUrl: 'https://github.com/LeGoffMael/video_editor',
  orientation: Orientation.portrait,
  description: 'A standalone video editor UI with trim, crop, rotate and cover selection.',
);
