// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/anwar907/flutter-clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock demo with simple splash screen.',
);
