// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Da Pixel',
  githubRepoUrl: 'https://github.com/mboonchai/da_pixel',
  orientation: Orientation.landscape,
  description: 'Pixel‑style clock demo for Raspberry Pi using Flutter and Flame.',
);
