// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Furniture App UI',
  githubRepoUrl: 'https://github.com/devefy/Flutter-Furniture-App-UI',
  orientation: Orientation.portrait,
  description: 'A stylish single‑screen furniture showcase UI for Flutter.',
);
