// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Sun Clock',
  githubRepoUrl: 'https://github.com/alainux/sun_clock',
  orientation: Orientation.landscape,
  description: 'A solar‑time clock face showing analog time, sun position, sunrise/set, and more.',
);
