// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Count By Clock',
  githubRepoUrl: 'https://github.com/meTowhid/count_by_clock',
  orientation: Orientation.landscape,
  description: 'Animated clock‑based digit display widget.',
);
