// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Give Collect Money',
  githubRepoUrl: 'https://github.com/himanshugarg08/flutter_give_collect_money',
  orientation: Orientation.portrait,
  description: 'A polished money‑transfer UI with custom animations, ready to run as a standalone Flutter app.',
);
