// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Adams Clock',
  githubRepoUrl: 'https://github.com/ahammer/adams_clock',
  orientation: Orientation.landscape,
  description: 'A visually striking, deterministic Time & Space clock rendered with custom canvas graphics.',
);
