// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Custom Calendar',
  githubRepoUrl: 'https://github.com/fluttercandies/flutter_custom_calendar',
  orientation: null,
  description: 'A customizable calendar widget with month and week views, selectable dates, and smooth view transitions.',
);
