// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Binary Clock',
  githubRepoUrl: 'https://github.com/fidelisakilan/binary_clock',
  orientation: Orientation.landscape,
  description: 'A binary clock showing time in binary columns.',
);
