// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterTodo',
  githubRepoUrl: 'https://github.com/MarcL01/FlutterTodo',
  orientation: Orientation.portrait,
  description: 'A visually appealing Todo UI with custom list tiles and hero animations.',
);
