// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Weatherdial',
  githubRepoUrl: 'https://github.com/jakesq/weatherdial',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock that visualizes weather conditions in real time.',
);
