// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/MRH1798/flutter_clock',
  orientation: Orientation.landscape,
  description: 'A sleek dark‑theme digital clock displayed on a single screen.',
);
