// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/Constans/flutter_clock',
  orientation: Orientation.landscape,
  description: 'Dash O\'Clock – an animated Flutter clock showing a day in 26 seconds.',
);
