// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'SuperHeroInteraction',
  githubRepoUrl: 'https://github.com/pinkeshdarji/SuperHeroInteraction',
  orientation: Orientation.portrait,
  description: 'A Flutter showcase of animated superhero cards with interactive transitions.',
);
