// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'NeonClock',
  githubRepoUrl: 'https://github.com/hanielbaez/neonClock',
  orientation: Orientation.landscape,
  description: 'A glowing neon clock built with Flutter and Rive.',
);
