// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Day Night Time Picker',
  githubRepoUrl: 'https://github.com/subhamayd2/day_night_time_picker',
  orientation: Orientation.portrait,
  description: 'A beautiful day/night animated time picker widget for Flutter.',
);
