// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Movie Details Ui',
  githubRepoUrl: 'https://github.com/roughike/movie-details-ui',
  orientation: Orientation.portrait,
  description: 'A beautiful, animated movie details page with arc banner and actor scroller.',
);
