// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock Lutter',
  githubRepoUrl: 'https://github.com/doctorcode9/analog_clock_lutter',
  orientation: Orientation.landscape,
  description: 'A standalone analog clock with animated hands.',
);
