// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Neumorphic Clock',
  githubRepoUrl: 'https://github.com/Puruchandra/Neumorphic-Clock',
  orientation: Orientation.portrait,
  description: 'A beautiful neumorphic clock widget with animated hands.',
);
