// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock App',
  githubRepoUrl: 'https://github.com/quickcodes/clock_app',
  orientation: Orientation.landscape,
  description: 'A clean always‑on minimal clock UI built with Flutter.',
);
