// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Shadow Clock',
  githubRepoUrl: 'https://github.com/SirusCodes/Shadow-Clock',
  orientation: Orientation.landscape,
  description: 'A stylish animated analog clock with shadow effects.',
);
