// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Mr.Clock',
  githubRepoUrl: 'https://github.com/ayushk0/Mr.Clock',
  orientation: Orientation.portrait,
  description: 'A simple yet elegant analog and digital clock UI.',
);
