// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Gradi Clock',
  githubRepoUrl: 'https://github.com/JankoLancer/gradi_clock',
  orientation: Orientation.landscape,
  description: 'A gradient clock face with animated stripes and digital time display.',
);
