// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Xkcd Clock',
  githubRepoUrl: 'https://github.com/csells/xkcd_clock',
  orientation: Orientation.landscape,
  description: 'Animated xkcd‑style clock rendered in Flutter.',
);
