// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Password Animation',
  githubRepoUrl: 'https://github.com/tunitowen/password_animation',
  orientation: Orientation.portrait,
  description: 'Animated password strength checker with dynamic validation feedback.',
);
