// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Infinity Flutter Clock',
  githubRepoUrl: 'https://github.com/AkashDivya/infinity_flutter_clock',
  orientation: Orientation.landscape,
  description: 'A visually striking, animated infinity clock for the Flutter Clock Challenge.',
);
