// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Animated Login Forms',
  githubRepoUrl: 'https://github.com/hammadx02/Flutter-Animated-Login-Forms',
  orientation: Orientation.portrait,
  description: 'Animated Rive login form demo with interactive UI.',
);
