// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flutters',
  githubRepoUrl: 'https://github.com/ecklf/flutters',
  orientation: Orientation.portrait,
  description: 'A Flappy‑bird style game built with Flutter and Flame, offering a lively single‑screen UI experience.',
);
