// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/maPer77/FlutterClock',
  orientation: Orientation.landscape,
  description: 'A self‑contained Flutter clock with animated UI.',
);
