// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Watch Clock',
  githubRepoUrl: 'https://github.com/AseemWangoo/watch_clock',
  orientation: Orientation.landscape,
  description: 'A standalone Flutter clock with animated hands displayed on a single canvas.',
);
