// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Driving Clock',
  githubRepoUrl: 'https://github.com/Yudeta/driving_clock',
  orientation: Orientation.landscape,
  description: 'Animated clock demo with moving hands and custom drawing.',
);
