// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Go',
  githubRepoUrl: 'https://github.com/justinmc/flutter-go',
  orientation: Orientation.landscape,
  description: 'Zoomable, pannable Go board with draggable pieces.',
);
