// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Vignettes',
  githubRepoUrl: 'https://github.com/gskinnerTeam/flutter_vignettes',
  orientation: null,
  description: 'Beautiful Flutter UI experiments',
);
