// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'HyperDrive',
  githubRepoUrl: 'https://github.com/atisamhaq123/HyperDrive',
  orientation: Orientation.landscape,
  description: 'A visually striking, animated futuristic clock built entirely in Flutter.',
);
