// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Onboarding Screen',
  githubRepoUrl: 'https://github.com/durannumit/flutter_onboarding_screen',
  orientation: Orientation.portrait,
  description: 'Animated onboarding screens with page‑drag gestures and reveal effects.',
);
