// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'How Is Moon',
  githubRepoUrl: 'https://github.com/Thomas-Leung/How-is-Moon',
  orientation: Orientation.landscape,
  description: 'Animated clock with moon phase display in a clean single‑screen UI.',
);
