// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Shimmer',
  githubRepoUrl: 'https://github.com/hnvn/flutter_shimmer',
  orientation: null,
  description: 'A shimmer effect widget for Flutter, providing a moving highlight over placeholder UI.',
);
