// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'CatClock',
  githubRepoUrl: 'https://github.com/imkcat/CatClock',
  orientation: Orientation.portrait,
  description: 'A beautiful animated sky clock that changes with time of day.',
);
