// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock',
  githubRepoUrl: 'https://github.com/TheAlphamerc/flutter_analog_clock',
  orientation: Orientation.landscape,
  description: 'A beautiful analog clock with light/dark themes and optional weather info.',
);
