// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'ClockWithAnimatedController',
  githubRepoUrl: 'https://github.com/Umigishi-Aoi/ClockWithAnimatedController',
  orientation: Orientation.landscape,
  description: 'Animated clock using AnimatedController in a self‑contained Flutter app.',
);
