// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Fantasy Clock',
  githubRepoUrl: 'https://github.com/CodeHipster/flutter-fantasy-clock',
  orientation: Orientation.landscape,
  description: 'A beautiful standalone analog and digital clock widget for Flutter.',
);
