// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'EV Car Dashboard Flutter',
  githubRepoUrl: 'https://github.com/abuanwar072/EV-Car-Dashboard-Flutter',
  orientation: Orientation.landscape,
  description: 'A sleek car HMI dashboard demo with animated speedometer, indicators, and gauges.',
);
