// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flip Clock',
  githubRepoUrl: 'https://github.com/echokk11/flutter_flip_clock',
  orientation: Orientation.landscape,
  description: 'A self‑contained flip clock with animated digit flips.',
);
