// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'My Clock',
  githubRepoUrl: 'https://github.com/ashumendra77/my_clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with color‑changing hands and background.',
);
