// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock',
  githubRepoUrl: 'https://github.com/rashidmrck/Clock',
  orientation: Orientation.landscape,
  description: 'A simple animated clock UI with a pulsing effect.',
);
