// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock24hour',
  githubRepoUrl: 'https://github.com/1984204066/clock24hour',
  orientation: Orientation.landscape,
  description: 'A 24‑hour analog clock with animated hands, ready to embed in any Flutter app.',
);
