// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Challenge',
  githubRepoUrl: 'https://github.com/AshirShaikh99/Flutter-Clock-Challenge',
  orientation: Orientation.landscape,
  description: 'Animated clock demo showcasing a custom Flutter UI component.',
);
