// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Squircle Study',
  githubRepoUrl: 'https://github.com/rydmike/squircle_study',
  orientation: Orientation.landscape,
  description: 'Interactive demo comparing various squircle shapes in Flutter.',
);
