// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FD Daily Task',
  githubRepoUrl: 'https://github.com/firgia/FD-Daily-Task',
  orientation: Orientation.landscape,
  description: 'A beautiful responsive daily‑task dashboard for web, mobile and desktop.',
);
