// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Credit Card Animation',
  githubRepoUrl: 'https://github.com/genabdulrehman/credit-card-animation',
  orientation: Orientation.portrait,
  description: 'Animated credit card showcase with smooth transitions.',
);
