// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Flip Clock',
  githubRepoUrl: 'https://github.com/kmeoung/flutter_flip_clock',
  orientation: Orientation.landscape,
  description: 'A standalone flip‑clock with animated flipping digits.',
);
