// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Login Home Animation',
  githubRepoUrl: 'https://github.com/GeekyAnts/flutter-login-home-animation',
  orientation: Orientation.portrait,
  description: 'Animated login screen with smooth transition to home view.',
);
