// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Digital Clock',
  githubRepoUrl: 'https://github.com/yatindeokar/digital_clock',
  orientation: Orientation.landscape,
  description: 'A galaxy‑styled animated digital clock with sun/moon indicators.',
);
