// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: '2048',
  githubRepoUrl: 'https://github.com/anuranBarman/2048',
  orientation: Orientation.landscape,
  description: 'A simple 2048 puzzle game with colorful grid and high‑score storage.',
);
