// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Gooey Tabbar Flutter',
  githubRepoUrl: 'https://github.com/wiltonribeiro/gooey_tabbar_flutter',
  orientation: Orientation.portrait,
  description: 'Animated Gooey Tab Bar component demo for Flutter.',
);
