// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Of Clocks Web',
  githubRepoUrl: 'https://github.com/egorbelibov/clock_of_clocks_web',
  orientation: Orientation.landscape,
  description: 'Animated clock UI demo that runs in the browser.',
);
