// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Ant Clock',
  githubRepoUrl: 'https://github.com/yerkbn/ant_clock',
  orientation: Orientation.landscape,
  description: 'A simple animated analog clock demo in Flutter.',
);
