// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Analog Clock',
  githubRepoUrl: 'https://github.com/Win-112/flutter_analog_clock',
  orientation: Orientation.landscape,
  description: 'Animated analog clock with light/dark themes and sample weather/location overlay.',
);
