// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Hover Effects',
  githubRepoUrl: 'https://github.com/wilsonowilson/Flutter-Hover-Effects',
  orientation: null,
  description: 'A showcase of CSS‑inspired hover effects for Flutter, displayed in an interactive carousel.',
);
