// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Public Demo',
  githubRepoUrl: 'https://github.com/joshuadeguzman/flutter-clock-public-demo',
  orientation: Orientation.landscape,
  description: 'A beautiful animated clock demo using Flutter and Rive.',
);
