// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Smooth Clock',
  githubRepoUrl: 'https://github.com/TheKingDave/smooth_clock',
  orientation: Orientation.landscape,
  description: 'A Flutter app showcasing smooth and binary clock visualizations.',
);
