// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Colorful Clock',
  githubRepoUrl: 'https://github.com/sundayglee/colorful_clock',
  orientation: Orientation.landscape,
  description: 'A vibrant, animated clock showing time, date, location, and weather.',
);
