// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Responsive Clock',
  githubRepoUrl: 'https://github.com/Mamun361054/flutter_responsive_clock',
  orientation: Orientation.landscape,
  description: 'A responsive Flutter clock that adapts to portrait and landscape layouts.',
);
