// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Cool Toolbar',
  githubRepoUrl: 'https://github.com/Roaa94/flutter_cool_toolbar',
  orientation: null,
  description: 'A visually striking, animated vertical toolbar demo in Flutter.',
);
