// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Clock Of Clocks',
  githubRepoUrl: 'https://github.com/HoseinHaqiqian/clock_of_clocks',
  orientation: Orientation.landscape,
  description: 'Animated numeric clock UI demo.',
);
