// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'D Art',
  githubRepoUrl: 'https://github.com/Solido/flutter-d-art',
  orientation: null,
  description: 'Generative d.Art: a standalone Flutter canvas showcasing animated, colorful patterns.',
);
