// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Paper Clock',
  githubRepoUrl: 'https://github.com/ryanjacktaylor/paper_clock',
  orientation: Orientation.landscape,
  description: 'A paper‑styled animated clock demo.',
);
