// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Taichi Clock',
  githubRepoUrl: 'https://github.com/xuyisheng/taichi_clock',
  orientation: Orientation.landscape,
  description: 'A Taichi‑styled clock with Chinese time symbols and animated hands.',
);
