// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Recursive Clock',
  githubRepoUrl: 'https://github.com/drogel/recursive_clock',
  orientation: Orientation.landscape,
  description: 'A recursive analog clock with nested rings showing time, weather, and location.',
);
