// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'FlutterClock',
  githubRepoUrl: 'https://github.com/zsmb13/FlutterClock',
  orientation: Orientation.landscape,
  description: 'A Flutter clock with animated digit columns updating every second.',
);
