// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Challenge Googlemaps',
  githubRepoUrl: 'https://github.com/flutter-ui-challenges/flutter_challenge_googlemaps',
  orientation: Orientation.portrait,
  description: 'A self‑contained, animated Google Maps redesign demo for Flutter.',
);
