// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'My Flutter Challenges',
  githubRepoUrl: 'https://github.com/pedromassango/my_flutter_challenges',
  orientation: Orientation.portrait,
  description: 'A set of standalone Flutter UI challenges with animations and custom widgets.',
);
