// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Login Ui',
  githubRepoUrl: 'https://github.com/MarcusNg/flutter_login_ui',
  orientation: Orientation.portrait,
  description: 'A polished login screen with custom styling and subtle animations.',
);
