// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Boating',
  githubRepoUrl: 'https://github.com/SpiciedCrab/Boating',
  orientation: Orientation.landscape,
  description: 'A beautiful animated analog clock with wave and bubble effects.',
);
