// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'Digital Alarm Clock Design',
  githubRepoUrl: 'https://github.com/codewithdarkwa/digital-alarm-clock-design',
  orientation: Orientation.portrait,
  description: 'A minimalist dark‑theme alarm clock with mint accents and custom time picker.',
);
