// AUTO-GENERATED by Flexer Showcase Discovery Agent
import 'package:showcase_library/showcase_contract.dart';
import 'package:flutter/widgets.dart';

const showcaseInfo = ShowcaseInfo(
  showcaseName: 'ClockApp',
  githubRepoUrl: 'https://github.com/gobindadasgithub/flutter_clockApp',
  orientation: Orientation.landscape,
  description: 'A simple animated clock using CustomPaint and StreamBuilder.',
);
